### ISSUE TITLE
[PAN-192] [PAN-71] Opción de volver atrás acciones (re-do / ctrl+z)

### ISSUE THREAD

**Issue by fagiannoni** [open-source-uc/planner#109]
Usar una cola de acciones para devolver acciones realizadas

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-71](https://linear.app/planner-uc/issue/PAN-71/opcion-de-volver-atras-acciones-re-do-ctrlz)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-71](https://linear.app/planner-uc/issue/PAN-71/opcion-de-volver-atras-acciones-re-do-ctrlz)</sub>

**Comment by Diegothx** [comment]
duplicado
