### ISSUE TITLE
[PAN-174] Permitir deseleccionar titulo (y quizas major y minor)

### ISSUE THREAD

**Issue by negamartin** [open-source-uc/planner#129]
<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-174](https://linear.app/planner-uc/issue/PAN-174/permitir-deseleccionar-titulo-y-quizas-major-y-minor)</sub>

**Comment by Diegothx** [comment]
Por ahora lo dejare como deseleccionar titulo y minor nomas
