### ISSUE TITLE
[Feat]: Validar correctamente si el limite es 55 o 65 creditos por semestre

### ISSUE THREAD

**Issue by kovaxis** [open-source-uc/planner#134]
A futuro, usar la informacion de cada estudiante para determinar el limite de creditos que tiene en cada semestre.

**Comment by negamartin** [comment]
Segun SIDING:

**Excepción A:**

Los alumnos podrán **optar a la excepción** de inscribir como máximo 60 ó 65cr. (cualquier combinación), de acuerdo a su rendimiento de los dos últimos semestres cursados:

1. Que aprueben un mínimo de 50cr. en cada uno de los últimos dos semestres, y
2. Que no hayan reprobado ni retirado ningún curso en los dos últimos semestres.

**Excepción B:**

Podrán **optar a la excepción** de inscribir como máximo 60 ó 65cr. (cualquier combinación), los alumnos de último año independiente de su rendimiento. Se entiende por último año aquellos alumnos que le falten 130 o menos créditos para Titularse.

**Excepción C:**

Podrán **optar a la excepción** de inscribir como máximo 60 ó 65cr. (cualquier combinación), los alumnos del Crr2013 de último año de su primer ciclo independiente de su rendimiento. Se entiende por último año aquellos alumnos que le falten 130 o menos créditos para Licenciarse.

**Comment by negamartin** [comment]
No creo que tengamos acceso a la información de los ramos retirados. Por ende, si hay un ramo echado en los últimos dos semestres o menos de 50cr podemos upgradear el warning a error, pero si no, dar un warning que diga esto mismo (eg. "tendrás que aprobar 50 creditos y no reprobar o retirar ningun ramo en los semestres 3 y 4 para poder tomar más de 55 créditos en el semestre 5").

De manera parecida, podemos cambiar este warning a incluir lo de la excepción B si cumple las condiciones. También, si cumple las condición B pero no la A evitar generar un error.

**Comment by kovaxis** [comment]
Esta feature es un poco imposible.

# Promover el warning a un error cuando se sabe que es ilegal

Un componente de esta feature es mostrar un error cuando el estudiante toma >55 créditos y se sabe que no puede hacerlo. Sin embargo, según SIDING:

> Excepción A:
>
> Los estudiantes podrán optar a la excepción de inscribir como máximo 60 ó 65cr. (cualquier combinación), de acuerdo a su rendimiento de los dos últimos semestres cursados:
>
>    1. Que aprueben un mínimo de 50cr. en cada uno de los últimos dos semestres, y
>    2. Que no hayan reprobado ni retirado ningún curso en los dos últimos semestres.
>
> Excepción B:
>
> Podrán optar a la excepción de inscribir como máximo 60 ó 65cr. (cualquier combinación), los estudiantes de último año independiente de su rendimiento. Se entiende por último año aquellos estudiantes que le falten 130 o menos créditos para Titularse.
>
> Excepción C:
>
> Podrán optar a la excepción de inscribir como máximo 60 ó 65cr. (cualquier combinación), los estudiantes de último año de su primer ciclo independiente de su rendimiento. Se entiende por último año aquellos estudiantes que le falten 130 o menos créditos para Licenciarse.

Osea que incluso si un estudiante ha reprobado cursos últimamente o tomado menos de 50 créditos, podría caer en las excepciones B y C, que son dificiles de formalizar, y probablemente requieren una petición especial a la DiPre.

# Suprimir el warning cuando se sabe que es legal

Otro componente de esta feature es suprimir el warning de >55 créditos cuando el estudiante cumple los requisitos para tomar 65 créditos. Estos son cuando los últimos 2 semestres cumplen ciertas condiciones.

Sin embargo, para semestres futuros no podemos predecir si el estudiante aprobará todos sus cursos o no. Por ende, solo podríamos implementar este feature para el semestre inmediatamente siguiente, y solo cuando no hay cursos en curso.

Para rematar, no tengo claro si SIDING nos entrega los cursos retirados, solo sabemos que nos entrega los cursos reprobados. Además, no tengo tan claro si el retiro único afecta la posibilidad de tomar 65 créditos.

Conclusión: incluso si resulta que SIDING nos entrega cursos retirados y retiro único, solo sería util para un caso borde muy particular, y no vale la pena agregar comportamiento especial para ese caso.
