### ISSUE TITLE
[PAN-169] Arreglo cursor grabber

### ISSUE THREAD

**Issue by Diegothx** [open-source-uc/planner#150]
* Por alguna razon, en algunos computadores el icono de grabber no carga 

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-169](https://linear.app/planner-uc/issue/PAN-169/arreglo-cursor-grabber)</sub>

**Comment by fagiannoni** [comment]
Cerraré esta issue, pero vuelve a abrirla si es que aún te ocurre el problema @shantifabri
