### ISSUE TITLE
[PAN-207] No eliminar elecciones del usuario al cambiar curriculumns

### ISSUE THREAD

**Issue by Diegothx** [open-source-uc/planner#168]
las elecciones de equivalencias que siguen en la planificacion y cursos extras no deberian borrarse a la hora de cambiar de major/minor/titulo.

**Comment by negamartin** [comment]
Quizás se podría cambiar el endpoint de `generate_plan` para recibir un argumento extra que indique desde qué semestre en adelante borrar los ramos y regenerarlos (pero teniendo en cuenta lo que el usuario tenía seleccionado en esos semestre, como las equivalencias y los ramos blancos).

Una forma de hacer lo de las equivalencias es hacerlas calzar por nombre. Si una equivalencia del plan nuevo tiene el mismo nombre que una equivalencia del plan antiguo, la equivalencia antigua tenía un ramo seleccionado y este ramo calza en la equivalencia nueva, la equivalencia nueva defaultea a la selección antigua.

Voy a implementarlo después de los ramos echados.

**Comment by negamartin** [comment]
(arreglado)
