### ISSUE TITLE
[PAN-213] Mover validación y generación al frontend

### ISSUE THREAD

**Issue by negamartin** [open-source-uc/planner#170]
Reduciría todo el riesgo de colapso del backend y mejoraría la experiencia del usuario.

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-213](https://linear.app/planner-uc/issue/PAN-213/mover-validacion-y-generacion-al-frontend)</sub>

**Comment by fagiannoni** [comment]
Cerraré esta issue porque ya mejoramos drásticamente la performance cacheando todo al inicio. @negamartin abrela de nuevo si es que crees que igual deberíamos hacer esto eventualmente.
