### ISSUE TITLE
[PAN-222] Permitir seleccionar cursos en el buscador haciendo click en el nombre

### ISSUE THREAD

**Issue by negamartin** [open-source-uc/planner#185]
Ahora mismo para seleccionar un curso hay que apretar en el radio circle. Seria bueno poder apretar cualquier lugar de la entrada del curso.

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-222](https://linear.app/planner-uc/issue/PAN-222/permitir-seleccionar-cursos-en-el-buscador-haciendo-click-en-el-nombre)</sub>

**Comment by Diegothx** [comment]
No lei que estaba como good first issue pero me la apropie jajaja

**Comment by negamartin** [comment]
jajsjasjjjdajj igual los good first issues hay que hacerlos igual, yo no me abstendria de hacer good first issues.
