### ISSUE TITLE
[Feat]: Mejorar estilo botones autofix

### ISSUE THREAD

**Issue by kovaxis** [open-source-uc/planner#187]
No se cual es el estilo por el que queremos ir, asi que lo dejo aquí.

**Comment by fagiannoni** [comment]
Nota para usuarios nuevos: los botones autofix son los que a veces aparecen en una advertencia o error para arreglar rapidamente el mensaje. Por ejemplo "Adelantar <curso>", "Atrasar <curso>" y "Agregar <curso>" en los errores de restricciones.
