### ISSUE TITLE
[PAN-224] Permitir scrollear más allá del último semestre

### ISSUE THREAD

**Issue by negamartin** [open-source-uc/planner#188]
Igual es medio incómodo que cuando estás trabajando con el último semestre forzosamente tienes que colocar el último semestre pegado al lado derecho de la pantalla (ie. no se puede scrollear más allá y dejarlo en el centro).

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-224](https://linear.app/planner-uc/issue/PAN-224/permitir-scrollear-mas-alla-del-ultimo-semestre)</sub>

**Comment by Diegothx** [comment]
Habia pensado que en una de esas podríamos dejar que los 2 semestres siguientes siempre se muestren (ahora se renderizan 2 semestres extras solo al estar haciendo drag), asi ademas si quieres poner ramos post tu ultimo semestre (post titulo, o quizas si aun no elijes titulo pero quieres agregar un curso al final) es mas directo que arrastrar un  curso al nuevo semestre y luego apretar + en este. Ademas asi no se tiene que renderizar y desrendizar esos semestres en cada arrastre. Tambien encontraba incomodo el como rebote que se da cuando termina el drag, que es causado por que se desrenderizan los ultimos semestres

**Comment by Diegothx** [comment]
Yo creo que con siempre tener 2 semestres extras + quizás un pequeño padding podría ser suficiente (? estoy en una branch haciendo reajustes del drag so probablemente la pruebe ahi

**Comment by negamartin** [comment]
me gusta eso, no lo habia pensado pero los rebotes tambien molestan.
