### ISSUE TITLE
[PAN-230] Hacer isConcrete parametro obligatorio

### ISSUE THREAD

**Issue by Diegothx** [open-source-uc/planner#195]
Por lo que entiendo estamos usando isConcrete para diferenciar entre cursos concretos y equivalencias, por lo cual no deberia ser obligatorio el parametro (actualmente en la practica siempre esta pero el client se genera con el parametro opcional)

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-230](https://linear.app/planner-uc/issue/PAN-230/hacer-isconcrete-parametro-obligatorio)</sub>

**Comment by negamartin** [comment]
Este es un problema medio tonto de parte del generador de cliente. Aunque no sea opcional, como tiene un default (`is_concrete=True` para `ConcreteId` y `is_concrete=False` para `EquivalenceId`) el generador lo toma como no-obligatorio.

Igual se podría solucionar a costa de un poco de redundancia en el backend (`ConcreteId(is_concrete=True, code=…)`). Voy a verlo.
