### ISSUE TITLE
[PAN-231] arreglar drag scroll

### ISSUE THREAD

**Issue by Diegothx** [open-source-uc/planner#199]
Aparentemente el scroll-dnd se detiene al salir de un drop area a otra (cada columna es un drop area), obviamente no queremos esto so hay que ver que se puede hacer

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-231](https://linear.app/planner-uc/issue/PAN-231/arreglar-drag-scroll)</sub>

**Comment by fagiannoni** [comment]
Esto ya está arreglado, no? @Diegothx
