### ISSUE TITLE
[PAN-234] Reparar Navbar

### ISSUE THREAD

**Issue by shantifabri** [open-source-uc/planner#201]
Por alguna razón, no solo la página seleccionada se muestra en color azul, si no que todas a excepción de cerrar/iniciar sesión. Esto incluye que el hover ya no funcione.

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-234](https://linear.app/planner-uc/issue/PAN-234/reparar-navbar)</sub>

**Comment by Diegothx** [comment]
Esto lo repare en la branch que hice, era porque quedaba desactualizado el metodo que ocupabamos de router para detectar la pagina actual con la actualización. Aun no arreglo esa PR pero dejare linkeado esta issue para el seguimiento

**Comment by shantifabri** [comment]
Si cache apenas hice la issue jaja
