### ISSUE TITLE
[PAN-235] Bug en errorTray, no he podido identificar que lo gatilla especificamente pero me ha salido 2 veces

### ISSUE THREAD

**Issue by Diegothx** [open-source-uc/planner#205]
![imagen.png](https://uploads.linear.app/0badc0ac-2b39-45d8-b72c-07d8d927829e/b8f4c3bf-0dd1-4576-b21f-52687b5237ff/5a8985f9-36b0-4a68-b045-7ae1a511e8b0)

<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-235](https://linear.app/planner-uc/issue/PAN-235/bug-en-errortray-no-he-podido-identificar-que-lo-gatilla)</sub>

**Comment by Diegothx** [comment]
Puede ser que era solo porque me faltaba una migracion, si me vuelve a salir aviso

**Comment by fagiannoni** [comment]
@Diegothx asumo que no te volvió a salir
