### ISSUE TITLE
[Feat]: Ajustar advertencia o error asignado a un semestre

### ISSUE THREAD

**Issue by Diegothx** [open-source-uc/planner#206]
Evitar que siga hasta el fin de la columna, se podría solo encasillar la parte del nombre del semestre quizás, sino requiere un poco de reajuste del componente columna. (la razón de porque pasa esto es que la columna se extiende para detectar drops mas abajo de la columna, so siempre toma el alto del planboard entero)

**Comment by fagiannoni** [comment]
No creo que sea un problema 🤔 pero es verdad que se vería más lindo si solamente encuadrara los cursos del semestre en vez de toda la columna.
