### ISSUE TITLE
[PAN-246] Scrapear 2023-2 en buscacursos el lunes

### ISSUE THREAD

**Issue by fagiannoni** [open-source-uc/planner#241]
<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-246](https://linear.app/planner-uc/issue/PAN-246/scrapear-2023-2-en-buscacursos-el-lunes)</sub>

**Comment by agucova** [comment]
Cuando buscacursos abra, hay que fetchear buscacursos en este [repo](https://github.com/negamartin/buscacursos-dl), empaquetar el resultado y actualizar el link al release aquí: https://github.com/open-source-uc/planner/blob/main/backend/app/sync/buscacursos_dl.py#L340-L345
