### ISSUE TITLE
[Bug]: Eliminar el warning de ramo no disponible para los ramos de titulo que aun no se han dictado

### ISSUE THREAD

**Issue by fagiannoni** [open-source-uc/planner#245]
Por ejemplo estos ramos que se empiezan a cursar el 2024-2 y 2025-1.
![image](https://github.com/open-source-uc/planner/assets/27508976/3bfbd14d-3acd-4345-b406-a8b90131ae1f)

**Comment by Diegothx** [comment]
Con el cambio del mensaje a "No hay registros que alguna vez se haya dictado el curso" asumo que ya estaría listo, puesto que por lo que entiendo no tenemos forma de distinguir entre cursos nuevos y extintos

**Comment by kovaxis** [comment]
Una buena forma seria analizar los planes, y si hay algún plan que obligatoriamente requiera un curso, ese curso se asume que se va a dar eventualmente.
