### ISSUE TITLE
[PAN-256] Integrar el ratelimiting con Redis y Caddy

### ISSUE THREAD

**Issue by fagiannoni** [open-source-uc/planner#252]
<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-256](https://linear.app/planner-uc/issue/PAN-256/integrar-el-ratelimiting-con-redis)</sub>

**Comment by agucova** [comment]
Contexto: En #208 se introdujo ratelimiting y en https://github.com/open-source-uc/planner/commit/7ba57123b32b25b60bb1da61f9ebaa0256ba3eca se introdujo Redis al setup de Docker Compose. Hay que integrar ambas features para que [`limits`](https://github.com/open-source-uc/planner/pull/208/files#diff-7a9fb05e404ca0dd496b751cef5895e2c729b880d8038808a0614347790af1acR11-R12) use la instancia de Redis disponible en la red interna (en el host `redis`).

**Comment by benjavicente** [comment]
Voy a intentar ver esto.
