### ISSUE TITLE
[Feat]: Hacer que la búsqueda de cursos sea instántanea

### ISSUE THREAD

**Issue by agucova** [open-source-uc/planner#295]

**Comment by fagiannoni** [comment]
No recuerdo el contexto de esta issue, @agucova puedes dar más detalles o sino la cerramos

**Comment by agucova** [comment]
@fagiannoni  La búsqueda de cursos debiese realizar la búsqueda a medida que tipeas, sin necesidad del botón adicional

**Comment by negamartin** [comment]
Seria nice hacer que la busqueda funcione en el frontend para hacer esto.

**Comment by kovaxis** [comment]
tags: busqueda en tiempo real, instantaneo, instantanea, frontend, filtro, buscar
