### ISSUE TITLE
[BUG]: Major Física

### ISSUE THREAD

**Issue by m0r0chit0** [open-source-uc/planner#305]
No aparece el major de física en las opciones de major :(

**Comment by agucova** [comment]
Lamentablemente, esto se debe a un problema de disponibilidad de ciertos majors especiales en SIDING. Intentaremos agregarlo apenas sea posible 😔

**Comment by m0r0chit0** [comment]
Yaaa bakan, gracias!

Enviado desde mi Samsung Mobile de Claro
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by crisalcaino99** [comment]
Aviso que tampoco sale el titulo de Ing Civil Mat.

**Comment by agucova** [comment]
La issue #307 sigue esta discusión. Perdonen!
