### ISSUE TITLE
[BUG]: Missing titulo ingemat 

### ISSUE THREAD

**Issue by jdelvalle2002** [open-source-uc/planner#306]
no aparece el plan: **(40023) Ingeniero Civil Matemático y Computacional (desde admisión 2020)**

cualquier duda con sus ramos etc me ofrezco a ayudar con la implmenetación :)

**Comment by agucova** [comment]
La issue #307 sigue esta discusión.

**Comment by jdelvalle2002** [comment]
gracias tkm <3
