### ISSUE TITLE
[FEAT]: <Problemas con semestralidad>

### ISSUE THREAD

**Issue by kevinjustiniano** [open-source-uc/planner#308]
# Problema
Al ingresar un nuevo ramo de título de eléctrica IEE3XXX y filtrar por semestralidad, los ramos que se dictan en semestres impares aparecen en el filtro de par, y los que se dictan en semestres pares en el filtro impar

## Comentarios

No sé si solo sea de eléctrica o de otros títulos o de otros ciclos

**Comment by Diegothx** [comment]
Efectivamente el filtro estaba dado vuelta, ya fue solucionado en el commit 7fd7a3d y deberia actualizarse en la pagina entre hoy y manana

**Comment by Diegothx** [comment]
Efectivamente el filtro estaba dado vuelta, ya fue solucionado en el commit 7fd7a3d y deberia actualizarse en la pagina entre hoy y manana

**Comment by Diegothx** [comment]
Efectivamente el filtro estaba dado vuelta, ya fue solucionado en el commit 7fd7a3d y deberia actualizarse en la pagina entre hoy y manana
