### ISSUE TITLE
[Bug]: Problema optativo de minor

### ISSUE THREAD

**Issue by DiegoVarela11** [open-source-uc/planner#321]
### Descripción

En la malla de major en transporte existe la opción de elegir programación avanzada, y teniendo en cuenta que mi minor es de amplitud en programación, donde programación avanzada es obligatorio, al tomar este ramo cuenta como avance de major y no minor, por lo que debo tomar un optativo de minor para completar los 50 créditos. En el planner no aparece la opción de elegir optativo de minor y toma programación avanzada como minor, por lo que arroja el error: "Faltan 10 créditos para el bloque Major -> Mínimos (LISTA 1)" y la advertencia: "Tienes 10 cŕeditos que no cuentan para tu curriculum", donde supuestamente tengo que elegir otro ramo de major.

![image](https://github.com/open-source-uc/planner/assets/101359901/f6b78441-9c3a-4652-a2b8-4a5f5913a25e)

**Comment by kovaxis** [comment]
Hola! Esto idealmente se arreglará con #353 . Gracias por tu observación! Nos fue muy útil para identificar casos borde.

**Comment by kovaxis** [comment]
Hola, hoy liberamos una nueva versión que debiera solucionar conflictos de major y minor como el tuyo. Podrías probar de nuevo?

**Comment by DiegoVarela11** [comment]
Hola, me funciona perfecto. Gracias!!
