### ISSUE TITLE
[Bug]: Ramos convalidados

### ISSUE THREAD

**Issue by matiasolivab** [open-source-uc/planner#325]
### Descripción

Los ramos convalidados no son contemplados por lo que se agregan cursos que ya fueron cursados.
Adjunto imagen:
![image](https://github.com/open-source-uc/planner/assets/127408943/cd0b6fdc-4c42-4aad-a6d5-57bfb28ce6aa)

**Comment by fagiannoni** [comment]
Hola @matiasolivab !

Podrías dar un poco más detalles sobre lo que hiciste para llegar a esa situación? Por ejemplo, se duplicó ese curso luego de usar un botón de autofix en una alerta? o quizás ocurrió al cambiar de Major/Minor/Titulo?

Gracias!

**Comment by fagiannoni** [comment]
Acabo de notar que no está repetido el curso, ya que son siglas distintas 🤔 EAE105A vs ICS1513. Eso puede significar que Siding no reconoce a EAE105A como una equivalencia de ICS1513.
