### ISSUE TITLE
Ramos faltantes minor data science

### ISSUE THREAD

**Issue by IanZmen** [open-source-uc/planner#328]
Hay 8 ramos opcionales, cuando en verdad son 11. Por ejemplo, falta IIC3423 big data. Aprovecho de decir que esta muy bueno el planner.

**Comment by Diegothx** [comment]
Esto quedo medio confuso desde nuestra parte, pero en resumen 'big data' (y los cursos faltantes) si aparece si sacas el filtro "Ocultar cursos no disponibles:" y aprietas buscar. Esto pasa porque ramos que ya no se dan y ramos nuevos por dar no son diferenciables (ya que la diferencia al final depende de si en el futuro los publican o no), por lo cual ambos quedan ocultos por default

**Comment by fagiannoni** [comment]
Exacto. Voy a cerrar este issue como resuelto, pero porfavor @IanZmen avísanos si es que sigues con dudas al respecto. También, si es que se te ocurre alguna mejor solución para esto puedes agregar otra issue pidiendo la funcionalidad.

Saludos! 👋
