### ISSUE TITLE
[Feat]: Confirmación Eliminar Malla

### ISSUE THREAD

**Issue by pepinofdz** [open-source-uc/planner#351]
### Descripción

Podría ser una buena idea agregar un popup que diga "¿Estas seguro que quieres eliminar <NOMBRE MALLA>? Esta acción no se puede revertir" al eliminar una malla.
Es solamente un detalle, y la página está excelente.
Gracias por su trabajo!

**Comment by fagiannoni** [comment]
Hola @pepinofdz !

Gracias por tu comentario! Ya se encuentra pedida esta funcionalidad en #317 🙌
