### ISSUE TITLE
[Feat]: Botón en el context menu para cambiar el bloque asociado a un ramo

### ISSUE THREAD

**Issue by Maratripa** [open-source-uc/planner#352]
### Descripción

Me pasa que algunos ramos que ya tomé son electivos de major y de minor y algunos los tomo para el major, otros para el minor, pero los que ya pasé me los etiqueta a todos como parte del minor, y me obliga a elegir un nuevo electivo de major, cuando ya lo tomé y tiene que ser uno de esos.

Este problema se podría solucionar si cuando selecciono un electivo de major, minor, exploratorio (tengo el mismo bug), revise si es un ramo que ya aprobé y lo saque de la malla.

**Comment by kovaxis** [comment]
Hola! Creo que esto se arreglaria con una combinacion de #353 y #354 . Cuando esté implementado te podríamos pedir que lo pruebes de nuevo? Gracias por la observación!

**Comment by Maratripa** [comment]
Súper, estaré atento a la actualización y lo pruebo :)
