### ISSUE TITLE
[Feat]: Endpoint administrador para "Ver planes alumno" desde Siding

### ISSUE THREAD

**Issue by fagiannoni** [open-source-uc/planner#358]
### Descripción

Esta funcionalidad es solo para administradores de la plataforma, no estudiantes.❗
En siding se agregará un botón de "ver planes del alumno" dentro de la vista de alumno. Para esto se debe implementar una ruta protegida con clave (ver como asociarlo a accesos de administrador) para ver un iFrame del planner directo en su vista de Siding, o quizás solo unas imagenes de los planes del alumno, o quizás solo el plan favorito del alumno (hay que preguntar bien a la DiPre qué es lo que necesitan aquí).

**Comment by kovaxis** [comment]
Desde la dipre prefieren una pestaña distinta sobre un iframe. Tambien, nos mencionaron que les gustaria algo asi como una banda que indique que se está viendo la vista de alumno, y también que como administrador no se guarden los cambios sobre la malla del alumno si se hace alguno.
