### ISSUE TITLE
[Fix]: No crashear cuando un alumno tiene inscrito un major/minor/titulo que no existe en Planner

### ISSUE THREAD

**Issue by kovaxis** [open-source-uc/planner#372]
### Descripción

Hasta ahora, cuando un alumno con el minor de matemática inscrito se conecta a Planner, planner crashea directamente. Planner debiera reconocer que el alumno tiene inscrito un minor que no existe, y no intentar cargarlo.

**Comment by agucova** [comment]
🧐
