### ISSUE TITLE
[Bug]: Refetchear base de datos de SIDING

### ISSUE THREAD

**Issue by vittocher** [open-source-uc/planner#374]
### Descripción

Si mi exploratorio fue el de robótica (IRB1010, que no es el mismo que Fundamentos de la Robótica) no me deja convalidarlo como optativo de exploración de majors. Me tira alerta de que necesito añadir un ramo de exploración de majors, pero ya está añadido IRB1010. (Con major robótica)

**Comment by kovaxis** [comment]
SIDING tiene agregado IRB1010 a la lista de exploratorios, es hora de actualizar.
