### ISSUE TITLE
[Feat]: AST1529 Como OFG

### ISSUE THREAD

**Issue by armas01** [open-source-uc/planner#379]
### Descripción

Hola, El ramo AST1529 (Planetas en el Universo) no está considerado como OFG, siendo que yo lo tengo aprobado como OFG en el Siding. Feliz de que lo actualicen para poder ver mi malla definitiva.

Saludos!

**Comment by kovaxis** [comment]
Hola, gracias con el reporte! Este ramo ya está en `dev`, solo falta revisar y aprobar las PRs faltantes para hacer deploy y publicarlo.
