### ISSUE TITLE
Minors de Profundidad Major Matematica

### ISSUE THREAD

**Issue by Cristian1754** [open-source-uc/planner#381]
### Descripción

Hola, escrbio debido a la falta de los minors de profundidad del major de matematica, los cuales constan del mismo listado de cursos del major para cada track, mas una lista de cursos optativos. Se agradeceria su inclusión.

Cristian Chávez.

**Comment by kovaxis** [comment]
Hola Cristián, gracias por el reporte!

Tenemos en cuenta las mallas que faltan en #307. En particular, los minors de matemática ya están listos, solo me falta resolver temas de retrocompatibilidad para publicarlos.
