### ISSUE TITLE
[Bug]: IHI0523 no aparece como OFG

### ISSUE THREAD

**Issue by gsinay** [open-source-uc/planner#406]
### Descripción

Hola!

El curso IHI0523 (Antropología Americana: Habitar, Reivindicar y Reconocer) No aparece como OFG Azul, solo figura como casilla gris. 

Gracias de antemano.

**Comment by kovaxis** [comment]
Esto se arreglará tras actualizar las mallas de SIDING, pero por alguna razón SIDING solo lo lista como OFG para C2022, no para C2020.

**Comment by kovaxis** [comment]
Deployeado :heavy_check_mark:
