### ISSUE TITLE
[Bug]: OFG's que no aparecen (IIC100G y TTF210)

### ISSUE THREAD

**Issue by antxnauta** [open-source-uc/planner#407]
### Descripción

No aparecen los ramos de "En búsqueda del bienestar: ¿qué nos dice la ciencia?" (IIC100G), OFG de Salud y Bienestar. Por otro lado, el ramo de "Religión y Fe ante el reto de la cultura moderna" fue reemplazado por "Experiencia Creyente y Secularismo" con el mismo profesor, Martin Becker. Fue confirmado por él mismo a inicio de semestre.

**Comment by kovaxis** [comment]
Hola, esto se arreglará cuando se publique la nueva versión que actualiza las definiciones desde SIDING. Lo único es que SIDING por alguna razón solo define Experiencia Creyente como teológico para C2022, no para C2020.
