### ISSUE TITLE
[Bug]: Vista admin - mantenedor de moderadores

### ISSUE THREAD

**Issue by spavea** [open-source-uc/planner#456]
### Descripción

Error:

![image](https://github.com/open-source-uc/planner/assets/171731639/f8fef914-0dcf-4945-82cd-487328a65f83)

![image](https://github.com/open-source-uc/planner/assets/171731639/43c51a39-8dea-4154-b5d4-8df232b8a45a)

**Comment by kovaxis** [comment]
Parece ocurrir por [este issue](https://github.com/pydantic/pydantic/issues/3836). Hay que ver como aplicar un workaround, o idealmente actualizar a Pydantic V2. Antes, el limitante era que [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen) no soportaba versiones nuevas de FastAPI, pero ahora existe [`openapi-ts`](https://github.com/hey-api/openapi-ts) que parece resolver el problema.

**Comment by kovaxis** [comment]
Arreglado en #465.
