### ISSUE TITLE
[Bug]: No crea una malla

### ISSUE THREAD

**Issue by bruverie** [open-source-uc/planner#460]
### Descripción

No me crea la malla y me entrega el error: Error al cargar plan Internal Server Error

**Comment by fagiannoni** [comment]
Hola @bruverie! Podrías revisar si ahora te funciona? Había un bug relacionado a la autenticación pero ya fue solucionado en #465 

Cerraré el issue, pero vuelve a comentar si te sigue ocurriendo 🙌
