### ISSUE TITLE
[Bug]: Error al cargar información del usuario

### ISSUE THREAD

**Issue by bifernandez** [open-source-uc/planner#462]
### Descripción

No me permite acceder a mis mallas o crear nuevas mallas al iniciar sesión ya que aparece constantemente el mensaje "Error al cargar la información del usuario" y vuelve a cargar la página.

**Comment by fagiannoni** [comment]
Hola @bifernandez! Había un bug con la autenticación luego de una actualización de Siding, pero ya fue solucionado en #465. Ahora te debería funcionar sin problemas 🚀
