### ISSUE TITLE
[Bug]: error al cargar la informacion del usuario

### ISSUE THREAD

**Issue by sschafern** [open-source-uc/planner#463]
### Descripción

no me deja acceder a mis mallas. sale el mensaje de "error al cargar informacion del usuario".

**Comment by bhenriquezsoto** [comment]
Mismo problema por aqui. Cache que esta intentando entrar con permiso de admin, moderador, cuando no es lo que se intenta.

<img width="453" alt="image" src="https://github.com/user-attachments/assets/41d8e934-d7e3-4328-8d5f-f0b11b323c4a">

**Comment by NicoJGutierrez** [comment]
Acá también, creo que está relacionado con que tenía una cuenta creada en el viejo planner.

**Comment by fagiannoni** [comment]
Hola @sschafern @bhenriquezsoto @NicoJGutierrez ! Había un bug con la autenticación luego de una actualización de Siding, pero ya fue solucionado en #465. Ahora les debería funcionar sin problemas 🚀
