### ISSUE TITLE
NOTA: Sobre estas issues

### ISSUE THREAD

**Issue by agucova** [open-source-uc/planner#53]
Las issues de este repositorio son rastreadas internamente en [Linear](https://linear.app) en vez de aquí. El workspace de Linear es, por ahora, privado. Debido a esto, usamos [Sync Linear](https://synclinear.com/) para sincronizar las issues con GitHub, incluyendo comentarios.

Esto es experimental y solo las nuevas issues se irán agregando de a poco. Hay también algunas issues antiguas que, sin embargo, aparecen como recientes.

**Comment by fagiannoni** [comment]
Dejamos de utilizar Linear, por lo que desde ahora las issues en github son las oficiales.
