### ISSUE TITLE
[PAN-186] [PAN-117] Eliminar prefijo de errores

### ISSUE THREAD

**Issue by agucova** [open-source-uc/planner#91]
<sub>From [SyncLinear.com](https://synclinear.com) | [PAN-117](https://linear.app/planner-uc/issue/PAN-117/eliminar-prefijo-de-errores)</sub>

<sub>[PAN-186](https://linear.app/planner-uc/issue/PAN-186/[pan-117]-eliminar-prefijo-de-errores)</sub>

**Comment by negamartin** [comment]
Se refiere al texto innecesario de "error: X", "warning: X" (redundante con el icono)
